
server:
  port: 8443

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/product/**
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/order/**
      - id: payment-service
        uri: lb://payment-service
        predicates:
        - Path=/api/payment/**
    
eureka:
  instance:
    hostname: host.docker.internal
    prefer-ip-address: false 
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}

# DEBUG = log matched routes | TRACE = log matched & unmatched routes    
logging:
  level:
    '[org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping]': TRACE
    
EUREKA_DEFAULTZONE_URL: http://${eureka.instance.hostname}:8761/eureka

  

